title: Site

options:
  changeStatus: false
  changeSlug: false
  delete: false

tabs:
  pages:
    label: Pages du site
    columns:
      main:
      - width: 1/2
        sections:
          pages:
            headline: Pages
            type: pages
            template: 
              - home
              - photographies
              - prestations
              - textes
              - a-propos
              - contact
              - mentions-legales
              - cgv
            create: true
            layout: list
            sortable: true
            images: false
  identite:
    label: Identité visuelle
    columns:
      main:
        width: 1/2
        sections:
          logo: 
            label: Logotype
            type: files
            layout: cards
            max: 1
            min: 1
            accept: 
              - image/svg+xml
              - image/png
              - image/x-png
              - image/jpeg
              - image/jpg
              - image/webp

  footer:
    label: Footer
    columns:
      main:
        width: 1/2
        sections:
          footercontent:
            type: fields
            fields:
              footer_credit:
                label: Crédit du site
                type: text
                placeholder: "Nom du site © année"